#!/bin/bash -e

MACHINE=${MACHINE:-ucm-imx8m-plus}
DISTRO=${DISTRO:-fslc-framebuffer}
EULA=1
T=$(dirname $(dirname $(readlink -f ${BASH_SOURCE[0]})))"/templates"

BD=$(cat <<< $@ | awk '$0=$NF')

if [[ -d ${BD} ]];then

echo "Back to the build environment ${BD}"
    source setup-environment ${BD}
else
    source setup-environment $@

for _d in ${T}/*;do
    _file=$(basename ${_d})
    for _f in ${_d}/*;do
        cat ${_f} >> conf/${_file}
    done;
done
fi
