#!/bin/bash -e

MACHINE=${MACHINE:-mcm-imx8m-mini}
DISTRO=${DISTRO:-fslc-x11}
EULA=1
T=$(dirname $(dirname $(readlink -f ${BASH_SOURCE[0]})))"/templates"

[[ -n ${NO_SETUP} ]] || source setup-environment $@

for _d in ${T}/*;do
    _file=$(basename ${_d})
    for _f in ${_d}/*;do
        cat ${_f} >> conf/${_file}
    done;
done
